version: 2

project_name: go-precommit

builds:
  - main: .
    binary: go-precommit
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w

archives:
  - formats: [binary]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

dockers_v2:
  - id: amd64
    image_templates:
      - "ghcr.io/miraccan00/go-precommit:{{ .Tag }}-amd64"
      - "ghcr.io/miraccan00/go-precommit:latest-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .Commit }}"
    dockerfile: Dockerfile.release
    goos: linux
    goarch: amd64

  - id: arm64
    image_templates:
      - "ghcr.io/miraccan00/go-precommit:{{ .Tag }}-arm64"
      - "ghcr.io/miraccan00/go-precommit:latest-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .Commit }}"
    dockerfile: Dockerfile.release
    goos: linux
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/miraccan00/go-precommit:{{ .Tag }}"
    image_templates:
      - "ghcr.io/miraccan00/go-precommit:{{ .Tag }}-amd64"
      - "ghcr.io/miraccan00/go-precommit:{{ .Tag }}-arm64"

  - name_template: "ghcr.io/miraccan00/go-precommit:latest"
    image_templates:
      - "ghcr.io/miraccan00/go-precommit:latest-amd64"
      - "ghcr.io/miraccan00/go-precommit:latest-arm64"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: miraccan00
    name: go-precommit
