package cmd

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"

	"github.com/spf13/cobra"
)

func newGlobalInstallCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "global-install",
		Short: "Install go-precommit as a global git hook for all repositories",
		Long: `Configures git globally so that go-precommit runs automatically in every
repository without per-project setup.

Two mechanisms are applied:
  1. core.hooksPath   — active immediately for all existing and future repos.
  2. init.templateDir — copies the hook into repos created with git init/clone.

Supports macOS, Linux, and Windows (Git for Windows).`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runGlobalInstall()
		},
	}
}

func newGlobalUninstallCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "global-uninstall",
		Short: "Remove the global go-precommit git hook configuration",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runGlobalUninstall()
		},
	}
}

var globalHookTypes = []string{"pre-commit", "pre-push"}

func runGlobalInstall() error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("resolving home directory: %w", err)
	}

	hooksDir := filepath.Join(home, ".config", "git", "hooks")
	for _, hookType := range globalHookTypes {
		if err := writeGlobalHook(hooksDir, hookType); err != nil {
			return err
		}
	}
	if err := gitConfigSet("core.hooksPath", toSlash(hooksDir)); err != nil {
		return err
	}
	fmt.Printf("core.hooksPath -> %s\n", hooksDir)

	templateDir := filepath.Join(home, ".git-templates")
	templateHooksDir := filepath.Join(templateDir, "hooks")
	for _, hookType := range globalHookTypes {
		if err := writeGlobalHook(templateHooksDir, hookType); err != nil {
			return err
		}
	}
	if err := gitConfigSet("init.templateDir", toSlash(templateDir)); err != nil {
		return err
	}
	fmt.Printf("init.templateDir -> %s\n", templateDir)

	fmt.Println("\nHooks installed: pre-commit, pre-push")
	fmt.Println("go-precommit is now active globally.")
	if runtime.GOOS == "windows" {
		fmt.Println("Requires Git for Windows: https://git-scm.com/download/win")
	}
	return nil
}

func runGlobalUninstall() error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("resolving home directory: %w", err)
	}

	for _, dir := range []string{
		filepath.Join(home, ".config", "git", "hooks"),
		filepath.Join(home, ".git-templates", "hooks"),
	} {
		for _, hookType := range globalHookTypes {
			path := filepath.Join(dir, hookType)
			if data, err := os.ReadFile(path); err == nil && isOurHook(string(data)) {
				_ = os.Remove(path)
				fmt.Printf("removed %s\n", path)
			}
		}
	}

	_ = gitConfigUnset("core.hooksPath")
	_ = gitConfigUnset("init.templateDir")
	fmt.Println("Global go-precommit configuration removed.")
	return nil
}

func writeGlobalHook(hooksDir, hookType string) error {
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return fmt.Errorf("creating %s: %w", hooksDir, err)
	}

	hookPath := filepath.Join(hooksDir, hookType)

	if existing, err := os.ReadFile(hookPath); err == nil && !isOurHook(string(existing)) {
		return fmt.Errorf("existing hook at %s is not managed by go-precommit; remove it first", hookPath)
	}

	// Git for Windows ships sh.exe so #!/bin/sh works on all platforms.
	script := fmt.Sprintf("#!/bin/sh\n# Installed by go-precommit\n# Do not edit this file manually.\ngo-precommit run --stage %s\n", hookType)
	if err := os.WriteFile(hookPath, []byte(script), 0o755); err != nil {
		return fmt.Errorf("writing hook to %s: %w", hookPath, err)
	}
	return nil
}

func gitConfigSet(key, value string) error {
	out, err := exec.Command("git", "config", "--global", key, value).CombinedOutput()
	if err != nil {
		return fmt.Errorf("git config --global %s: %w\n%s", key, err, out)
	}
	return nil
}

func gitConfigUnset(key string) error {
	out, err := exec.Command("git", "config", "--global", "--unset", key).CombinedOutput()
	if err != nil {
		return fmt.Errorf("git config --global --unset %s: %w\n%s", key, err, out)
	}
	return nil
}

// toSlash converts Windows backslashes to forward slashes for git config values.
func toSlash(path string) string {
	if runtime.GOOS != "windows" {
		return path
	}
	result := make([]byte, len(path))
	for i := range path {
		if path[i] == '\\' {
			result[i] = '/'
		} else {
			result[i] = path[i]
		}
	}
	return string(result)
}
