package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

func newInstallCmd() *cobra.Command {
	var hookType string

	cmd := &cobra.Command{
		Use:   "install",
		Short: "Install the pre-commit git hook",
		Long: `Installs go-precommit as a git hook in the current repository.
Writes .git/hooks/pre-commit pointing to the current binary.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runInstall(hookType)
		},
	}

	cmd.Flags().StringVar(&hookType, "hook-type", "pre-commit", "Hook type to install (pre-commit, pre-push, commit-msg)")
	return cmd
}

func runInstall(hookType string) error {
	gitDir, err := findGitDir(".")
	if err != nil {
		return fmt.Errorf("not in a git repository: %w", err)
	}

	hooksDir := filepath.Join(gitDir, "hooks")
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return fmt.Errorf("creating hooks directory: %w", err)
	}

	hookPath := filepath.Join(hooksDir, hookType)

	// Check if a non-go-precommit hook already exists
	if existing, err := os.ReadFile(hookPath); err == nil {
		content := string(existing)
		if len(content) > 0 && !isOurHook(content) {
			return fmt.Errorf("existing hook at %s is not managed by go-precommit; remove it first", hookPath)
		}
	}

	exePath, err := os.Executable()
	if err != nil {
		exePath = "go-precommit"
	}

	hookContent := fmt.Sprintf("#!/bin/sh\n# Installed by go-precommit\n# Do not edit this file manually.\n%s run --stage %s\n", exePath, hookType)

	if err := os.WriteFile(hookPath, []byte(hookContent), 0o755); err != nil {
		return fmt.Errorf("writing hook file: %w", err)
	}

	fmt.Printf("go-precommit hook installed at %s\n", hookPath)
	return nil
}

func isOurHook(content string) bool {
	return strings.Contains(content, "go-precommit")
}

// findGitDir walks up from startPath to find the .git directory.
func findGitDir(startPath string) (string, error) {
	path, err := filepath.Abs(startPath)
	if err != nil {
		return "", err
	}

	for {
		gitPath := filepath.Join(path, ".git")
		if info, err := os.Stat(gitPath); err == nil && info.IsDir() {
			return gitPath, nil
		}
		parent := filepath.Dir(path)
		if parent == path {
			return "", fmt.Errorf(".git directory not found")
		}
		path = parent
	}
}
